# Generated by Django 4.2.5 on 2024-03-02 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_category_featuredproduct_page'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FeaturedProduct',
        ),
    ]
