# Generated by Django 4.2.5 on 2024-03-03 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_product_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
    ]
