# Generated by Django 4.2.5 on 2024-03-03 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_cartitem_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='order',
            name='subtotal',
        ),
        migrations.RemoveField(
            model_name='order',
            name='total',
        ),
    ]
