# Generated by Django 4.2.5 on 2024-03-03 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_remove_order_created_at_remove_order_subtotal_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='user',
        ),
    ]
